apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dealer-service-hpa
  namespace: scrapzee
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: dealer-service
  targetCPUUtilizationPercentage: 60