apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: scrapzee
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: frontend
  targetCPUUtilizationPercentage: 60