apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: scrapzee
  namespace: argocd
spec:
  description: Scrapzee GitOps Project

  sourceRepos:
    - "https://github.com/Sagarrrsh/scrapzee-k8s.git"

  destinations:
    - namespace: scrapzee
      server: https://kubernetes.default.svc
    - namespace: argo-rollouts
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet   

    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
    - group: argoproj.io
      kind: AnalysisRun

    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: Event

    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy

    - group: autoscaling
      kind: HorizontalPodAutoscaler
