---
# Stable service - receives production traffic
apiVersion: v1
kind: Service
metadata:
  name: frontend-stable
  namespace: scrapzee
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

---
# Canary service - receives canary traffic
apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
  namespace: scrapzee
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

---
# Main service - backward compatibility
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: scrapzee
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
