apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: auth-service
  namespace: scrapzee
  labels:
    app: auth-service
    tier: backend
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: auth-service
  
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      containers:
        - name: auth-service
          image: sagar1003/scrapzee-auth-api:v1
          ports:
            - containerPort: 5001
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: scrapzee-db-secrets
                  key: auth-db-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: scrapzee-secrets
                  key: jwt-secret

  strategy:
    canary:
      canaryService: auth-service-canary
      stableService: auth-service-stable
      
      trafficRouting:
        nginx:
          stableIngress: scrapzee-ingress
      
      steps:
        - setWeight: 20
        - pause: {duration: 2m}
        - setWeight: 50
        - pause: {duration: 3m}
        - setWeight: 80
        - pause: {duration: 1m}



