apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dealer-service
  namespace: scrapzee
  labels:
    app: dealer-service
    tier: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dealer-service
  
  template:
    metadata:
      labels:
        app: dealer-service
        tier: backend
    spec:
      containers:
        - name: dealer-service
          image: sagar1003/scrapzee-dealer-api:v2
          ports:
            - containerPort: 5000
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: scrapzee-db-secrets
                  key: dealer-db-url
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.scrapzee.svc.cluster.local"
            - name: USER_SERVICE_URL
              value: "http://user-service.scrapzee.svc.cluster.local"

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

  strategy:
    canary:
      canaryService: dealer-service-canary
      stableService: dealer-service-stable
      
      trafficRouting:
        nginx:
          stableIngress: scrapzee-ingress
      
      steps:
        - setWeight: 20
        - pause: {duration: 2m}
        - setWeight: 50
        - pause: {duration: 3m}
        - setWeight: 80

        - pause: {duration: 1m}
