# SECRET (MySQL Root Password)

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: scrapzee
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password


---

# CONFIGMAP (Database Init Script)

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: scrapzee
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS scrapzee_auth;
    CREATE DATABASE IF NOT EXISTS scrapzee_pricing;
    CREATE DATABASE IF NOT EXISTS scrapzee_users;
    CREATE DATABASE IF NOT EXISTS scrapzee_dealers;

    CREATE USER IF NOT EXISTS 'scrapzee'@'%' IDENTIFIED BY 'scrapzee123';

    GRANT ALL PRIVILEGES ON scrapzee_auth.* TO 'scrapzee'@'%';
    GRANT ALL PRIVILEGES ON scrapzee_pricing.* TO 'scrapzee'@'%';
    GRANT ALL PRIVILEGES ON scrapzee_users.* TO 'scrapzee'@'%';
    GRANT ALL PRIVILEGES ON scrapzee_dealers.* TO 'scrapzee'@'%';

    FLUSH PRIVILEGES;


---
# HEADLESS SERVICE (Required for StatefulSet)

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: scrapzee
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306


---
# STATEFULSET

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: scrapzee
spec:
  serviceName: mysql
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

          ports:
            - containerPort: 3306

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 6

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mysql-init
          configMap:
            name: mysql-init

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
